# -*- coding: utf-8 -*-

CITY_LOCALE = {
	"Abidjan": "fr_CI",
	"Accra": "en_GH",
	"Adak": "en_US",
	"Addis Ababa": "am_ET",
	"Adelaide": "en_AU",
	"Aden": "ar_YE",
	"Algiers": "ar_DZ",
	"Almaty": "kk_KZ",
	"Amman": "ar_JO",
	"Amsterdam": "nl_NL",
	"Anadyr": "ru_RU",
	"Anchorage": "en_US",
	"Andorra": "ca_AD",
	"Anguilla": "en_AI",
	"Antananarivo": "fr_MG",
	"Antigua": "en_AG",
	"Apia": "en_WS",
	"Aqtau": "kk_KZ",
	"Aqtobe": "kk_KZ",
	"Araguaina": "pt_BR",
	"Aruba": "nl_AW",
	"Ashgabat": "tk_TM",
	"Asmara": "ar_ER",
	"Astrakhan": "ru_RU",
	"Asuncion": "es_PY",
	"Athens": "el_GR",
	"Atikokan": "en_CA",
	"Atyrau": "kk_KZ",
	"Auckland": "en_NZ",
	"Azores": "pt_PT",
	"Baghdad": "ar_IQ",
	"Bahia": "pt_BR",
	"Bahia Banderas": "es_MX",
	"Bahrain": "ar_BH",
	"Baku": "az_AZ",
	"Bamako": "fr_ML",
	"Bangkok": "th_TH",
	"Bangui": "fr_CF",
	"Banjul": "en_GM",
	"Barbados": "en_BB",
	"Barnaul": "ru_RU",
	"Beirut": "ar_LB",
	"Belem": "pt_BR",
	"Belgrade": "sr_RS",
	"Belize": "en_BZ",
	"Berlin": "de_DE",
	"Bermuda": "en_BM",
	"Beulah": "en_US",
	"Bishkek": "ky_KG",
	"Bissau": "pt_GW",
	"Blanc-Sablon": "en_CA",
	"Blantyre": "en_MW",
	"Boa Vista": "pt_BR",
	"Bogota": "es_CO",
	"Boise": "en_US",
	"Bougainville": "en_PG",
	"Bratislava": "sk_SK",
	"Brazzaville": "fr_CG",
	"Brisbane": "en_AU",
	"Broken Hill": "en_AU",
	"Brunei": "ms_BN",
	"Brussels": "fr_BE",
	"Bucharest": "ro_RO",
	"Budapest": "hu_HU",
	"Buenos Aires": "es_AR",
	"Bujumbura": "fr_BI",
	"Busingen": "de_DE",
	"Cairo": "ar_EG",
	"Cambridge Bay": "en_CA",
	"Campo Grande": "pt_BR",
	"Canary": "es_ES",
	"Cancun": "es_MX",
	"Cape Verde": "pt_CV",
	"Caracas": "es_VE",
	"Casey": "en_AQ",
	"Catamarca": "es_AR",
	"Cayenne": "fr_GF",
	"Cayman": "en_KY",
	"Center": "en_US",
	"Ceuta": "es_ES",
	"Chagos": "en_IO",
	"Chatham": "en_NZ",
	"Chicago": "en_US",
	"Chihuahua": "es_MX",
	"Chisinau": "ru_MD",
	"Chita": "ru_RU",
	"Choibalsan": "mn_MN",
	"Christmas": "en_CX",
	"Chuuk": "en_FM",
	"Ciudad Juarez": "es_MX",
	"Cocos": "en_CC",
	"Colombo": "si_LK",
	"Comoro": "ar_KM",
	"Conakry": "fr_GN",
	"Copenhagen": "da_DK",
	"Cordoba": "es_AR",
	"Costa Rica": "es_CR",
	"Creston": "en_CA",
	"Cuiaba": "pt_BR",
	"Curacao": "en_CW",
	"Dakar": "fr_SN",
	"Damascus": "ar_SY",
	"Danmarkshavn": "kl_GL",
	"Dar es Salaam": "en_TZ",
	"Darwin": "en_AU",
	"Davis": "en_AQ",
	"Dawson": "en_CA",
	"Dawson Creek": "en_CA",
	"Denver": "en_US",
	"Detroit": "en_US",
	"Dhaka": "bn_BD",
	"Dili": "pt_TL",
	"Djibouti": "ar_DJ",
	"Dominica": "en_DM",
	"Douala": "en_CM",
	"Dubai": "ar_AE",
	"Dublin": "en_IE",
	"DumontDUrville": "en_AQ",
	"Dushanbe": "tg_TJ",
	"Easter": "es_CL",
	"Edmonton": "en_CA",
	"Efate": "en_VU",
	"Eirunepe": "pt_BR",
	"El Aaiun": "ar_MA",
	"El Salvador": "es_SV",
	"Eucla": "en_AU",
	"Fakaofo": "en_TK",
	"Famagusta": "el_CY",
	"Faroe": "fo_FO",
	"Fiji": "en_FJ",
	"Fort Nelson": "en_CA",
	"Fortaleza": "pt_BR",
	"Freetown": "en_SL",
	"Funafuti": "en_TV",
	"Gaborone": "en_BW",
	"Galapagos": "es_EC",
	"Gambier": "fr_PF",
	"Gaza": "ar_PS",
	"Gibraltar": "en_GI",
	"Glace Bay": "en_CA",
	"Goose Bay": "en_CA",
	"Grand Turk": "en_TC",
	"Grenada": "en_GD",
	"Guadalcanal": "en_SB",
	"Guadeloupe": "fr_GP",
	"Guam": "en_GU",
	"Guatemala": "es_GT",
	"Guayaquil": "es_EC",
	"Guernsey": "en_GG",
	"Guyana": "en_GY",
	"Halifax": "en_CA",
	"Harare": "en_ZW",
	"Havana": "es_CU",
	"Hebron": "ar_PS",
	"Helsinki": "fi_FI",
	"Hermosillo": "es_MX",
	"Ho Chi Minh": "vi_VN",
	"Hobart": "en_AU",
	"Hong Kong": "en_HK",
	"Honolulu": "en_US",
	"Hovd": "mn_MN",
	"Indianapolis": "en_US",
	"Inuvik": "en_CA",
	"Iqaluit": "en_CA",
	"Irkutsk": "ru_RU",
	"Isle of Man": "en_IM",
	"Istanbul": "tr_TR",
	"Jakarta": "in_ID",
	"Jamaica": "en_JM",
	"Jayapura": "in_ID",
	"Jersey": "en_JE",
	"Jerusalem": "he_IL",
	"Johannesburg": "en_ZA",
	"Juba": "en_SS",
	"Jujuy": "es_AR",
	"Juneau": "en_US",
	"Kabul": "fa_AF",
	"Kaliningrad": "ru_RU",
	"Kamchatka": "ru_RU",
	"Kampala": "en_UG",
	"Kanton": "en_KI",
	"Karachi": "en_PK",
	"Kathmandu": "ne_NP",
	"Kerguelen": "fr_TF,",
	"Khandyga": "ru_RU",
	"Khartoum": "en_SD",
	"Kigali": "fr_RW",
	"Kinshasa": "fr_CD",
	"Kiritimati": "en_KI",
	"Kirov": "ru_RU",
	"Knox": "en_US",
	"Kolkata": "en_IN",
	"Kosrae": "en_FM",
	"Kralendijk": "nl_BQ",
	"Krasnoyarsk": "ru_RU",
	"Kuala Lumpur": "ms_MY",
	"Kuching": "ms_MY",
	"Kuwait": "ar_KW",
	"Kwajalein": "en_MH",
	"Kyiv": "uk_UA",
	"La Paz": "es_BO",
	"La Rioja": "es_AR",
	"Lagos": "en_NG",
	"Libreville": "fr_GA",
	"Lima": "es_PE",
	"Lindeman": "en_AU",
	"Lisbon": "pt_PT",
	"Ljubljana": "sl_SI",
	"Lome": "fr_TG",
	"London": "en_GB",
	"Longyearbyen": "no_SJ",
	"Lord Howe": "en_AU",
	"Los Angeles": "en_US",
	"Louisville": "en_US",
	"Lower Princes": "en_SX",
	"Luanda": "pt_AO",
	"Lubumbashi": "fr_CD",
	"Lusaka": "en_ZM",
	"Luxembourg": "lb_LU",
	"Macau": "pt_MO",
	"Maceio": "pt_BR",
	"Macquarie": "en_AU",
	"Madeira": "pt_PT",
	"Madrid": "es_ES",
	"Magadan": "ru_RU",
	"Mahe": "en_SC",
	"Majuro": "en_MH",
	"Makassar": "in_ID",
	"Malabo": "es_GQ",
	"Maldives": "dv_MV",
	"Malta": "mt_MT",
	"Managua": "es_NI",
	"Manaus": "pt_BR",
	"Manila": "fil_PH",
	"Maputo": "pt_MZ",
	"Marengo": "en_US",
	"Mariehamn": "sv_AX",
	"Marigot": "fr_MF",
	"Marquesas": "fr_PF",
	"Martinique": "fr_MQ",
	"Maseru": "en_LS",
	"Matamoros": "es_MX",
	"Mauritius": "en_MU",
	"Mawson": "en_AQ",
	"Mayotte": "fr_YT",
	"Mazatlan": "es_MX",
	"Mbabane": "en_SZ",
	"McMurdo": "en_AQ",
	"Melbourne": "en_AU",
	"Mendoza": "es_AR",
	"Menominee": "en_US",
	"Merida": "es_MX",
	"Metlakatla": "en_US",
	"Mexico City": "es_MX",
	"Midway": "en_UM",
	"Minsk": "be_BY",
	"Miquelon": "fr_PM",
	"Mogadishu": "ar_SO",
	"Monaco": "fr_MC",
	"Moncton": "en_CA",
	"Monrovia": "en_LR",
	"Monterrey": "es_MX",
	"Montevideo": "es_UY",
	"Monticello": "en_US",
	"Montserrat": "en_MS",
	"Moscow": "ru_RU",
	"Muscat": "ar_OM",
	"Nairobi": "en_KE",
	"Nassau": "en_BS",
	"Nauru": "en_NR",
	"Ndjamena": "ar_TD",
	"New Salem": "en_US",
	"New York": "en_US",
	"Niamey": "fr_NE",
	"Nicosia": "el_CY",
	"Niue": "en_NU",
	"Nome": "en_US",
	"Norfolk": "en_NF",
	"Noronha": "pt_BR",
	"Nouakchott": "ar_MR",
	"Noumea": "fr_NC",
	"Novokuznetsk": "ru_RU",
	"Novosibirsk": "ru_RU",
	"Nuuk": "kl_GL",
	"Ojinaga": "es_MX",
	"Omsk": "ru_RU",
	"Oral": "kk_KZ",
	"Oslo": "no_NO",
	"Ouagadougou": "fr_BF",
	"Pago Pago": "en_AS",
	"Palau": "en_PW",
	"Palmer": "en_AQ",
	"Panama": "es_PA",
	"Paramaribo": "nl_SR",
	"Paris": "fr_FR",
	"Perth": "en_AU",
	"Petersburg": "en_US",
	"Phnom Penh": "km_KH",
	"Phoenix": "en_US",
	"Pitcairn": "en_PN",
	"Podgorica": "sr_ME",
	"Pohnpei": "en_FM",
	"Pontianak": "in_ID",
	"Port Moresby": "en_PG",
	"Port of Spain": "en_TT",
	"Port-au-Prince": "fr_HT",
	"Porto Velho": "pt_BR",
	"Porto-Novo": "fr_BJ",
	"Prague": "cs_CZ",
	"Puerto Rico": "es_PR",
	"Punta Arenas": "es_CL",
	"Pyongyang": "ko_KP",
	"Qatar": "ar_QA",
	"Qostanay": "kk_KZ",
	"Qyzylorda": "kk_KZ",
	"Rankin Inlet": "en_CA",
	"Rarotonga": "en_CK",
	"Recife": "pt_BR",
	"Regina": "en_CA",
	"Resolute": "en_CA",
	"Reunion": "fr_RE",
	"Reykjavik": "is_IS",
	"Riga": "lv_LV",
	"Rio Branco": "pt_BR",
	"Rio Gallegos": "es_AR",
	"Riyadh": "ar_SA",
	"Rome": "it_IT",
	"Rothera": "en_AQ",
	"Saipan": "en_MP",
	"Sakhalin": "ru_RU",
	"Salta": "es_AR",
	"Samara": "ru_RU",
	"Samarkand": "zu_UZ",
	"San Juan": "es_AR",
	"San Luis": "es_AR",
	"San Marino": "it_SM",
	"Santarem": "pt_BR",
	"Santiago": "es_CL",
	"Santo Domingo": "es_DO",
	"Sao Paulo": "pt_BR",
	"Sao Tome": "pt_ST",
	"Sarajevo": "hr_BA",
	"Saratov": "ru_RU",
	"Scoresbysund": "kl_GL",
	"Seoul": "ko_KR",
	"Shanghai": "zh_CN",
	"Simferopol": "uk_UA",
	"Singapore": "en_SG",
	"Sitka": "en_US",
	"Skopje": "mk_MK",
	"Sofia": "bg_BG",
	"South Georgia": "en_GS",
	"Srednekolymsk": "ru_RU",
	"St Barthelemy": "fr_BL",
	"St Helena": "en_SH",
	"St Johns": "en_CA",
	"St Kitts": "en_KN",
	"St Lucia": "en_LC",
	"St Thomas": "en_VI",
	"St Vincent": "en_VC",
	"Stanley": "en_FK",
	"Stockholm": "sv_SE",
	"Swift Current": "en_CA",
	"Sydney": "en_AU",
	"Syowa": "en_AQ",
	"Tahiti": "fr_PF",
	"Taipei": "zh_TW",
	"Tallinn": "et_EE",
	"Tarawa": "en_KI",
	"Tashkent": "zu_UZ",
	"Tbilisi": "ka_GE",
	"Tegucigalpa": "es_HN",
	"Tehran": "fa_IR",
	"Tell City": "en_US",
	"Thimphu": "dz_BT",
	"Thule": "kl_GL",
	"Tijuana": "es_MX",
	"Tirane": "sq_AL",
	"Tokyo": "ja_JP",
	"Tomsk": "ru_RU",
	"Tongatapu": "en_TO",
	"Toronto": "en_CA",
	"Tortola": "en_VG",
	"Tripoli": "ar_LY",
	"Troll": "en_AQ",
	"Tucuman": "es_AR",
	"Tunis": "ar_TN",
	"Ulaanbaatar": "mn_MN",
	"Ulyanovsk": "ru_RU",
	"Urumqi": "zh_CN",
	"Ushuaia": "es_AR",
	"Ust-Nera": "ru_RU",
	"Vaduz": "de_LI",
	"Vancouver": "en_CA",
	"Vatican": "it_VA",
	"Vevay": "en_US",
	"Vienna": "de_AT",
	"Vientiane": "lo_LA",
	"Vilnius": "lt_LT",
	"Vincennes": "en_US",
	"Vladivostok": "ru_RU",
	"Volgograd": "ru_RU",
	"Vostok": "en_AQ",
	"Wake": "en_UM",
	"Wallis": "fr_WF",
	"Warsaw": "pl_PL",
	"Whitehorse": "en_CA",
	"Winamac": "en_US",
	"Windhoek": "en_NA",
	"Winnipeg": "en_CA",
	"Yakutat": "en_US",
	"Yakutsk": "ru_RU",
	"Yangon": "my_MM",
	"Yekaterinburg": "ru_RU",
	"Yerevan": "hy_AM",
	"Zagreb": "hr_HR",
	"Zurich": "de_CH",
}
